apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      {% if nginx.initContainers.enabled %}
      initContainers:
        - name: init-sleep
          image: busybox
          command: ['sh', '-c', 'echo "Sleeping for 10 seconds..." && sleep 10']
      {% endif %}
      containers:
        - name: nginx
          image: nginx:{{ nginx.imageTag }}
          ports:
            - containerPort: 80