apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: kluctl-experiment
spec:
  interval: 5m
  source:
    git:
      url: https://github.com/dag-andersen/kluctl-experiment.git
      path: "./apps"
  timeout: 2m
  target: {{ args.env }}
  prune: true
  delete: true
  manual: false